name: reactiontest
description: Test your reaction

publish_to: 'none'

version: 1.1.1+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  in_app_review: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_mobile_ads: ^0.13.4
  provider: ^6.0.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  rename: ^1.3.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/