name: reactiontest
description: Test your reaction
publish_to: none
version: 1.1.7+14
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  google_mobile_ads: ^1.2.0
  in_app_review: ^2.0.4
  shared_preferences: ^2.0.13
  url_strategy: ^0.2.0

dev_dependencies:
  carapacik_lints:
    git:
      url: https://github.com/Carapacik/carapacik_lints.git
#  flutter_launcher_icons_maker: ^0.10.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env

#flutter_icons:
#  android: true
#  ios: true
#  web: true
#  windows: true
#  image_path: assets/icon.png
