name: reactiontest
description: Simple reaction test

publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_launcher_icons: "^0.9.0"
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.webp"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/