name: reactiontest
description: Test your reaction
publish_to: 'none'
version: 1.1.9+17
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^2.0.0
  in_app_review: ^2.0.4
  shared_preferences: ^2.0.15
  url_strategy: ^0.2.0

dev_dependencies:
  carapacik_lints: ^1.1.3
  icons_launcher: ^2.0.2

flutter:
  uses-material-design: true

icons_launcher:
  image_path: 'assets/ic_logo_border.png'
  platforms:
    android:
      enable: true
      adaptive_background_image: 'assets/ic_background.png'
      adaptive_foreground_image: 'assets/ic_foreground.png'
      adaptive_round_image: 'assets/ic_foreground.png'
    ios:
      enable: true
      image_path: 'assets/ic_logo.png'
    web:
      enable: true
      image_path: 'assets/ic_logo_border.png'
      favicon_path: 'assets/ic_logo_border.png'
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true
