name: reactiontest
description: Test your reaction
publish_to: 'none'

version: 1.1.2+8

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  google_mobile_ads: ^1.0.1
  in_app_review: ^2.0.4
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_launcher_icons_maker: ^0.10.2
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - .env